config:
  plugin:
    metrics-by-endpoint: {}
  target: "http://localhost:3000"
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
  - name: "Sessions Flow(generate random user + create user)"
    flow:
      - get:
          url: "/faker"
          capture:
            - json: "$.name"
              as: "name"
            - json: "$.lastname"
              as: "lastname"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: "Creando el usuario: {{ email }}"
      - post:
          url: "/api/users"
          json: #este json represernta el body
            name: "{{ name }}"
            lastname: "{{ lastname }}"
            email: "{{ email }}"
            password: "{{ password }}"
