info:
  title: Product API
  version: 1.0.0
  tags: Products
paths:
  /api/products:
    get:
      summary: Get products
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductsResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Successful response
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /{id}:
    put:
      summary: Update a product
      parameters:
        - $ref: "#/components/parameters/IdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Successful response
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      summary: Delete a product
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
    ProductsResponse:
      type: object
      properties:
        status:
          type: string
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
    DeleteResponse:
      type: object
      properties:
        message:
          type: string
        id:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
  parameters:
    IdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
